### ISSUE TITLE
Demonstrate how unit tests work into the workflow

### ISSUE THREAD

**Issue by zenflow** [mariusschulz/npm-babel-example#1]
As titled: Demonstrate how unit tests work into the workflow

What should the package.js `"scripts"` section look like

**Comment by mariusschulz** [comment]
Hey @zenflow! Running your test suite is indeed a crucial part of the development workflow. @alexjoverm et al have done a great job with [typescript-library-starter](https://github.com/alexjoverm/typescript-library-starter), so I recommend you check out the default [`package.json`](https://github.com/alexjoverm/typescript-library-starter/blob/master/package.json) that ships with the template. Hope this helps!

(I'm closing this issue here because I'm no longer actively updating this repository.)

**Comment by zenflow** [comment]
Thank you for your help @mariusschulz !
